name = "zapfdruck"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
name = "zapfdruck"

[env.preview]
name = "zapfdruck-preview"

[vars]
ENVIRONMENT = "production"
